package problems_1_to_25;

public class Problem_02_EvenFibonacci {
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	
	public static int sumOfEvenFibonaccis(){
		int sum = 0;
		int firstTerm = 1;
		int secondTerm = 2;
		while(secondTerm <= 4000000  || firstTerm <=4000000){
			 if(secondTerm % 2 == 0){
				sum = sum + secondTerm;
			}
			
			int tempSumOfTwoFib = firstTerm + secondTerm;
			firstTerm = secondTerm;
			secondTerm = tempSumOfTwoFib;
		}
		return sum;
	}

	public static void main(String[] args) {
		System.out.println("Answer: " + 4613732  + "\nResult: " + sumOfEvenFibonaccis());

	}

}
